using System;

namespace Scifa.UnionTypes;

/// <summary>
/// Indicates that the annotated type is a union type and should have its content generated by the Scifa.UnionTypes generator.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
public sealed class UnionTypeAttribute : Attribute
{
}